server:
  servlet:
    context-path: /test
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
springdoc:
  swagger-ui:
    path: product-swagger-ui
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/